#!/usr/bin/env python3
"""Copy hero gallery image per matched course from sitepro/gallery_gen/ into
redesign/assets/images/golf/courses/{country-slug}-{course-slug}.{ext}.

Reads redesign/docs/COURSE_MAP.csv produced by build_course_map.py.
"""
import csv
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REDESIGN = ROOT / "redesign"
SITEPRO = ROOT / "sitepro"
GALLERY = SITEPRO / "gallery_gen"
CSV_PATH = REDESIGN / "docs" / "COURSE_MAP.csv"
DEST_DIR = REDESIGN / "assets" / "images" / "golf" / "courses"
IMAGE_MAP_OUT = REDESIGN / "docs" / "IMAGE_MAP.md"


def main():
    DEST_DIR.mkdir(parents=True, exist_ok=True)
    copies = []
    misses = []
    with CSV_PATH.open(encoding="utf-8") as fh:
        for row in csv.DictReader(fh):
            if row["status"] != "matched":
                continue
            h = row["hero_hash"]
            ext = row["hero_ext"] or "jpg"
            if not h:
                misses.append(row)
                continue
            src = GALLERY / f"{h}_gallery.{ext}"
            if not src.exists():
                misses.append(row)
                continue
            dest_name = f"{row['country_slug']}-{row['course_slug']}.{ext}"
            dest = DEST_DIR / dest_name
            shutil.copyfile(src, dest)
            copies.append((row, dest_name))

    # Write IMAGE_MAP.md
    with IMAGE_MAP_OUT.open("w", encoding="utf-8") as fh:
        fh.write("# Course image map\n\nGenerated by `redesign/tools/extract_hero_images.py`.\n\n")
        fh.write("| Country | Course | Source hash | Destination |\n|---|---|---|---|\n")
        for row, name in copies:
            fh.write(f"| {row['country_name']} | {row['course_name']} | `{row['hero_hash'][:12]}…` | `assets/images/golf/courses/{name}` |\n")

    print(f"Copied {len(copies)} hero images → {DEST_DIR}")
    if misses:
        print(f"\nMissing source for {len(misses)} matched courses:")
        for row in misses:
            print(f"  - {row['country_slug']}/{row['course_slug']} (hash={row['hero_hash']!r})")


if __name__ == "__main__":
    main()
