#!/usr/bin/env python3
"""Copy a hero image per matched course from sitepro/gallery_gen/ into
redesign/assets/images/golf/courses/{country-slug}-{course-slug}.{ext}.

For each course in legacy-php order, walk through that page's image list and
claim the FIRST hash not already used by another course. If every hash in the
page's gallery is already claimed (because two legacy pages literally share an
identical gallery), fall back to the country hero image.
"""
import csv
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
REDESIGN = ROOT / "redesign"
SITEPRO = ROOT / "sitepro"
GALLERY = SITEPRO / "gallery_gen"
CSV_PATH = REDESIGN / "docs" / "COURSE_MAP.csv"
COURSES_DIR = REDESIGN / "assets" / "images" / "golf" / "courses"
COUNTRY_DIR = REDESIGN / "assets" / "images" / "golf"
IMAGE_MAP_OUT = REDESIGN / "docs" / "IMAGE_MAP.md"

COUNTRY_FALLBACK = {
    "scotland": "scotland-st-andrews.jpg",
    "ireland": "ireland-ballyliffin.jpg",
    "wales": "scotland-st-andrews.jpg",
    "spain": "spain-barcelona.jpg",
    "portugal": "portugal-algarve.jpg",
    "france": "spain-barcelona.jpg",
    "italy": "italy-milan.jpg",
    "netherlands": "netherlands-amsterdam.jpg",
    "germany": "netherlands-amsterdam.jpg",
    "switzerland": "italy-milan.jpg",
    "greece": "greece-costa-navarino.jpg",
    "sweden": "netherlands-amsterdam.jpg",
    "denmark": "netherlands-amsterdam.jpg",
    "norway": "netherlands-amsterdam.jpg",
}


def parse_hashes(field: str) -> list[tuple[str, str]]:
    """all_hashes column is "hash1:ext1|hash2:ext2|…" — return [(hash,ext), …]."""
    out = []
    if not field:
        return out
    for part in field.split("|"):
        if ":" in part:
            h, ext = part.split(":", 1)
            out.append((h, ext))
    return out


def main():
    COURSES_DIR.mkdir(parents=True, exist_ok=True)
    for f in COURSES_DIR.glob("*"):
        f.unlink()

    claimed_hashes: set[str] = set()
    copies = []
    fallback_used = []

    with CSV_PATH.open(encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))

    # Process in legacy_php numeric order so the lowest-numbered legacy page wins
    # the first unique image; later pages walk past the shared prefix.
    rows.sort(key=lambda r: (int(r["legacy_php"]) if r["legacy_php"].isdigit() else 9999,
                              r["country_slug"], r["course_slug"]))

    for row in rows:
        if row["status"] not in ("matched", "image-only"):
            continue
        country = row["country_slug"]
        hashes = parse_hashes(row.get("all_hashes", ""))

        # Find the first hash not yet claimed by another page.
        chosen = None
        for h, ext in hashes:
            if h in claimed_hashes:
                continue
            src = GALLERY / f"{h}_gallery.{ext}"
            if not src.exists():
                continue
            chosen = (h, ext, src)
            break

        if chosen:
            h, ext, src = chosen
            # Consume the entire gallery so later pages with shared prefixes
            # skip past them and find truly-unique imagery.
            for hh, _ in hashes:
                claimed_hashes.add(hh)
            dest_name = f"{country}-{row['course_slug']}.{ext}"
            shutil.copyfile(src, COURSES_DIR / dest_name)
            copies.append((row, dest_name, "legacy", h))
            continue

        # Whole gallery already claimed → country fallback
        fb = COUNTRY_FALLBACK.get(country)
        if not fb:
            print(f"  no fallback for {country}")
            continue
        fb_src = COUNTRY_DIR / fb
        if not fb_src.exists():
            print(f"  fallback missing on disk: {fb}")
            continue
        dest_ext = fb_src.suffix.lstrip(".")
        dest_name = f"{country}-{row['course_slug']}.{dest_ext}"
        shutil.copyfile(fb_src, COURSES_DIR / dest_name)
        copies.append((row, dest_name, "fallback", ""))
        fallback_used.append(row["course_slug"])

    with IMAGE_MAP_OUT.open("w", encoding="utf-8") as fh:
        fh.write("# Course image map\n\nGenerated by `redesign/tools/extract_hero_images.py`.\n\n")
        fh.write("| Country | Course | Source | Destination |\n|---|---|---|---|\n")
        for row, name, source, h in copies:
            if source == "legacy":
                src_label = f"`{h[:12]}…` (legacy gallery)"
            else:
                src_label = f"country fallback `{COUNTRY_FALLBACK[row['country_slug']]}` (legacy gallery fully shared with another page)"
            fh.write(f"| {row['country_name']} | {row['course_name']} | {src_label} | `assets/images/golf/courses/{name}` |\n")

    print(f"Copied {len(copies)} hero images → {COURSES_DIR}")
    print(f"  {len(copies) - len(fallback_used)} unique-legacy, {len(fallback_used)} country fallback")
    if fallback_used:
        print("  fully-shared gallery (fallback applied):")
        for s in fallback_used:
            print(f"    - {s}")


if __name__ == "__main__":
    main()
